### ISSUE TITLE
error when running "import pyltr"

### ISSUE THREAD

**Issue by Ulden** [jma127/pyltr#1]
```
     10 
---> 11 import data
     12 import metrics
     13 import models

ImportError: No module named 'data'
```

import error under python3.5.1, no matter install pyltr or import directly from the source files.

**Comment by jma127** [comment]
Hi Gioro, pyltr has only been tested on 2.7 so far. I've been wanting to
fix compatibility for some time, but am unsure as to when I'll get to it.
Sorry for the inconvenience.
- Jerry

**Comment by jma127** [comment]
Closed by https://github.com/jma127/pyltr/pull/2
